name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x 

      - name: Publish Blazor WASM
        run: dotnet publish -c Release -o build_output

      - name: Fix base href for GitHub Pages
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/StickerMaker\/" \/>/' build_output/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build_output/wwwroot
          publish_branch: gh-pages
